#!/bin/sh

echo "Running linter..."
npm run lint
if [ $? -ne 0 ]; then
  echo "Linter failed. Commit aborted."
  exit 1
fi

echo "Running unit tests..."
npm run test
if [ $? -ne 0 ]; then
  echo "Unit tests failed. Commit aborted."
  exit 1
fi

echo "All checks passed!"
